package com.dy.model;

public class Advice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_advice.adviceid
     *
     * @mbggenerated
     */
    private Integer adviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_advice.patientid
     *
     * @mbggenerated
     */
    private Integer patientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_advice.doctorid
     *
     * @mbggenerated
     */
    private Integer doctorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_advice.subjectid
     *
     * @mbggenerated
     */
    private Integer subjectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_advice.advicecontent
     *
     * @mbggenerated
     */
    private String advicecontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_advice.advicedate
     *
     * @mbggenerated
     */
    private String advicedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_advice.adviceanswer
     *
     * @mbggenerated
     */
    private String adviceanswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_advice.adviceanswerdate
     *
     * @mbggenerated
     */
    private String adviceanswerdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_advice.isanswer
     *
     * @mbggenerated
     */
    private String isanswer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_advice.adviceid
     *
     * @return the value of ssm_advice.adviceid
     *
     * @mbggenerated
     */
    public Integer getAdviceid() {
        return adviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_advice.adviceid
     *
     * @param adviceid the value for ssm_advice.adviceid
     *
     * @mbggenerated
     */
    public void setAdviceid(Integer adviceid) {
        this.adviceid = adviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_advice.patientid
     *
     * @return the value of ssm_advice.patientid
     *
     * @mbggenerated
     */
    public Integer getPatientid() {
        return patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_advice.patientid
     *
     * @param patientid the value for ssm_advice.patientid
     *
     * @mbggenerated
     */
    public void setPatientid(Integer patientid) {
        this.patientid = patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_advice.doctorid
     *
     * @return the value of ssm_advice.doctorid
     *
     * @mbggenerated
     */
    public Integer getDoctorid() {
        return doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_advice.doctorid
     *
     * @param doctorid the value for ssm_advice.doctorid
     *
     * @mbggenerated
     */
    public void setDoctorid(Integer doctorid) {
        this.doctorid = doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_advice.subjectid
     *
     * @return the value of ssm_advice.subjectid
     *
     * @mbggenerated
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_advice.subjectid
     *
     * @param subjectid the value for ssm_advice.subjectid
     *
     * @mbggenerated
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_advice.advicecontent
     *
     * @return the value of ssm_advice.advicecontent
     *
     * @mbggenerated
     */
    public String getAdvicecontent() {
        return advicecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_advice.advicecontent
     *
     * @param advicecontent the value for ssm_advice.advicecontent
     *
     * @mbggenerated
     */
    public void setAdvicecontent(String advicecontent) {
        this.advicecontent = advicecontent == null ? null : advicecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_advice.advicedate
     *
     * @return the value of ssm_advice.advicedate
     *
     * @mbggenerated
     */
    public String getAdvicedate() {
        return advicedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_advice.advicedate
     *
     * @param advicedate the value for ssm_advice.advicedate
     *
     * @mbggenerated
     */
    public void setAdvicedate(String advicedate) {
        this.advicedate = advicedate == null ? null : advicedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_advice.adviceanswer
     *
     * @return the value of ssm_advice.adviceanswer
     *
     * @mbggenerated
     */
    public String getAdviceanswer() {
        return adviceanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_advice.adviceanswer
     *
     * @param adviceanswer the value for ssm_advice.adviceanswer
     *
     * @mbggenerated
     */
    public void setAdviceanswer(String adviceanswer) {
        this.adviceanswer = adviceanswer == null ? null : adviceanswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_advice.adviceanswerdate
     *
     * @return the value of ssm_advice.adviceanswerdate
     *
     * @mbggenerated
     */
    public String getAdviceanswerdate() {
        return adviceanswerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_advice.adviceanswerdate
     *
     * @param adviceanswerdate the value for ssm_advice.adviceanswerdate
     *
     * @mbggenerated
     */
    public void setAdviceanswerdate(String adviceanswerdate) {
        this.adviceanswerdate = adviceanswerdate == null ? null : adviceanswerdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_advice.isanswer
     *
     * @return the value of ssm_advice.isanswer
     *
     * @mbggenerated
     */
    public String getIsanswer() {
        return isanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_advice.isanswer
     *
     * @param isanswer the value for ssm_advice.isanswer
     *
     * @mbggenerated
     */
    public void setIsanswer(String isanswer) {
        this.isanswer = isanswer == null ? null : isanswer.trim();
    }
}