package com.dy.model;

public class Business {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_business.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_business.menucode
     *
     * @mbggenerated
     */
    private String menucode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_business.businesscode
     *
     * @mbggenerated
     */
    private String businesscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_business.businessname
     *
     * @mbggenerated
     */
    private String businessname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_business.businessnamekey
     *
     * @mbggenerated
     */
    private String businessnamekey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_business.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_business.id
     *
     * @return the value of ssm_business.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_business.id
     *
     * @param id the value for ssm_business.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_business.menucode
     *
     * @return the value of ssm_business.menucode
     *
     * @mbggenerated
     */
    public String getMenucode() {
        return menucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_business.menucode
     *
     * @param menucode the value for ssm_business.menucode
     *
     * @mbggenerated
     */
    public void setMenucode(String menucode) {
        this.menucode = menucode == null ? null : menucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_business.businesscode
     *
     * @return the value of ssm_business.businesscode
     *
     * @mbggenerated
     */
    public String getBusinesscode() {
        return businesscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_business.businesscode
     *
     * @param businesscode the value for ssm_business.businesscode
     *
     * @mbggenerated
     */
    public void setBusinesscode(String businesscode) {
        this.businesscode = businesscode == null ? null : businesscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_business.businessname
     *
     * @return the value of ssm_business.businessname
     *
     * @mbggenerated
     */
    public String getBusinessname() {
        return businessname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_business.businessname
     *
     * @param businessname the value for ssm_business.businessname
     *
     * @mbggenerated
     */
    public void setBusinessname(String businessname) {
        this.businessname = businessname == null ? null : businessname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_business.businessnamekey
     *
     * @return the value of ssm_business.businessnamekey
     *
     * @mbggenerated
     */
    public String getBusinessnamekey() {
        return businessnamekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_business.businessnamekey
     *
     * @param businessnamekey the value for ssm_business.businessnamekey
     *
     * @mbggenerated
     */
    public void setBusinessnamekey(String businessnamekey) {
        this.businessnamekey = businessnamekey == null ? null : businessnamekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_business.url
     *
     * @return the value of ssm_business.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_business.url
     *
     * @param url the value for ssm_business.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

	@Override
	public String toString() {
		return "Business [id=" + id + ", menucode=" + menucode
				+ ", businesscode=" + businesscode + ", businessname="
				+ businessname + ", businessnamekey=" + businessnamekey
				+ ", url=" + url + "]";
	}
    
}