package com.dy.model;

public class Evaluate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_evaluate.evaluateid
     *
     * @mbggenerated
     */
    private Integer evaluateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_evaluate.doctorid
     *
     * @mbggenerated
     */
    private Integer doctorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_evaluate.patientid
     *
     * @mbggenerated
     */
    private Integer patientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_evaluate.evaluatelevel
     *
     * @mbggenerated
     */
    private String evaluatelevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_evaluate.evaluatecontent
     *
     * @mbggenerated
     */
    private String evaluatecontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_evaluate.evaluatedate
     *
     * @mbggenerated
     */
    private String evaluatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_evaluate.evaluateid
     *
     * @return the value of ssm_evaluate.evaluateid
     *
     * @mbggenerated
     */
    public Integer getEvaluateid() {
        return evaluateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_evaluate.evaluateid
     *
     * @param evaluateid the value for ssm_evaluate.evaluateid
     *
     * @mbggenerated
     */
    public void setEvaluateid(Integer evaluateid) {
        this.evaluateid = evaluateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_evaluate.doctorid
     *
     * @return the value of ssm_evaluate.doctorid
     *
     * @mbggenerated
     */
    public Integer getDoctorid() {
        return doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_evaluate.doctorid
     *
     * @param doctorid the value for ssm_evaluate.doctorid
     *
     * @mbggenerated
     */
    public void setDoctorid(Integer doctorid) {
        this.doctorid = doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_evaluate.patientid
     *
     * @return the value of ssm_evaluate.patientid
     *
     * @mbggenerated
     */
    public Integer getPatientid() {
        return patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_evaluate.patientid
     *
     * @param patientid the value for ssm_evaluate.patientid
     *
     * @mbggenerated
     */
    public void setPatientid(Integer patientid) {
        this.patientid = patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_evaluate.evaluatelevel
     *
     * @return the value of ssm_evaluate.evaluatelevel
     *
     * @mbggenerated
     */
    public String getEvaluatelevel() {
        return evaluatelevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_evaluate.evaluatelevel
     *
     * @param evaluatelevel the value for ssm_evaluate.evaluatelevel
     *
     * @mbggenerated
     */
    public void setEvaluatelevel(String evaluatelevel) {
        this.evaluatelevel = evaluatelevel == null ? null : evaluatelevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_evaluate.evaluatecontent
     *
     * @return the value of ssm_evaluate.evaluatecontent
     *
     * @mbggenerated
     */
    public String getEvaluatecontent() {
        return evaluatecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_evaluate.evaluatecontent
     *
     * @param evaluatecontent the value for ssm_evaluate.evaluatecontent
     *
     * @mbggenerated
     */
    public void setEvaluatecontent(String evaluatecontent) {
        this.evaluatecontent = evaluatecontent == null ? null : evaluatecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_evaluate.evaluatedate
     *
     * @return the value of ssm_evaluate.evaluatedate
     *
     * @mbggenerated
     */
    public String getEvaluatedate() {
        return evaluatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_evaluate.evaluatedate
     *
     * @param evaluatedate the value for ssm_evaluate.evaluatedate
     *
     * @mbggenerated
     */
    public void setEvaluatedate(String evaluatedate) {
        this.evaluatedate = evaluatedate == null ? null : evaluatedate.trim();
    }
}