package com.dy.model;

public class Fee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_fee.feeid
     *
     * @mbggenerated
     */
    private Integer feeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_fee.caseid
     *
     * @mbggenerated
     */
    private Integer caseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_fee.feecategory
     *
     * @mbggenerated
     */
    private String feecategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_fee.medicinalid
     *
     * @mbggenerated
     */
    private Integer medicinalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_fee.medicinalnum
     *
     * @mbggenerated
     */
    private Integer medicinalnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_fee.feeid
     *
     * @return the value of ssm_fee.feeid
     *
     * @mbggenerated
     */
    public Integer getFeeid() {
        return feeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_fee.feeid
     *
     * @param feeid the value for ssm_fee.feeid
     *
     * @mbggenerated
     */
    public void setFeeid(Integer feeid) {
        this.feeid = feeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_fee.caseid
     *
     * @return the value of ssm_fee.caseid
     *
     * @mbggenerated
     */
    public Integer getCaseid() {
        return caseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_fee.caseid
     *
     * @param caseid the value for ssm_fee.caseid
     *
     * @mbggenerated
     */
    public void setCaseid(Integer caseid) {
        this.caseid = caseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_fee.feecategory
     *
     * @return the value of ssm_fee.feecategory
     *
     * @mbggenerated
     */
    public String getFeecategory() {
        return feecategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_fee.feecategory
     *
     * @param feecategory the value for ssm_fee.feecategory
     *
     * @mbggenerated
     */
    public void setFeecategory(String feecategory) {
        this.feecategory = feecategory == null ? null : feecategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_fee.medicinalid
     *
     * @return the value of ssm_fee.medicinalid
     *
     * @mbggenerated
     */
    public Integer getMedicinalid() {
        return medicinalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_fee.medicinalid
     *
     * @param medicinalid the value for ssm_fee.medicinalid
     *
     * @mbggenerated
     */
    public void setMedicinalid(Integer medicinalid) {
        this.medicinalid = medicinalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_fee.medicinalnum
     *
     * @return the value of ssm_fee.medicinalnum
     *
     * @mbggenerated
     */
    public Integer getMedicinalnum() {
        return medicinalnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_fee.medicinalnum
     *
     * @param medicinalnum the value for ssm_fee.medicinalnum
     *
     * @mbggenerated
     */
    public void setMedicinalnum(Integer medicinalnum) {
        this.medicinalnum = medicinalnum;
    }
}