package com.dy.model;

public class Manager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_manager.managerid
     *
     * @mbggenerated
     */
    private Integer managerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_manager.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_manager.managerrealname
     *
     * @mbggenerated
     */
    private String managerrealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_manager.usertype
     *
     * @mbggenerated
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_manager.phonenum
     *
     * @mbggenerated
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_manager.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_manager.isemailIdentify
     *
     * @mbggenerated
     */
    private String isemailidentify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_manager.isphoneIdentify
     *
     * @mbggenerated
     */
    private String isphoneidentify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_manager.managersex
     *
     * @mbggenerated
     */
    private String managersex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_manager.managerbrith
     *
     * @mbggenerated
     */
    private String managerbrith;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_manager.managerid
     *
     * @return the value of ssm_manager.managerid
     *
     * @mbggenerated
     */
    public Integer getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_manager.managerid
     *
     * @param managerid the value for ssm_manager.managerid
     *
     * @mbggenerated
     */
    public void setManagerid(Integer managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_manager.userid
     *
     * @return the value of ssm_manager.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_manager.userid
     *
     * @param userid the value for ssm_manager.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_manager.managerrealname
     *
     * @return the value of ssm_manager.managerrealname
     *
     * @mbggenerated
     */
    public String getManagerrealname() {
        return managerrealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_manager.managerrealname
     *
     * @param managerrealname the value for ssm_manager.managerrealname
     *
     * @mbggenerated
     */
    public void setManagerrealname(String managerrealname) {
        this.managerrealname = managerrealname == null ? null : managerrealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_manager.usertype
     *
     * @return the value of ssm_manager.usertype
     *
     * @mbggenerated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_manager.usertype
     *
     * @param usertype the value for ssm_manager.usertype
     *
     * @mbggenerated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_manager.phonenum
     *
     * @return the value of ssm_manager.phonenum
     *
     * @mbggenerated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_manager.phonenum
     *
     * @param phonenum the value for ssm_manager.phonenum
     *
     * @mbggenerated
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_manager.email
     *
     * @return the value of ssm_manager.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_manager.email
     *
     * @param email the value for ssm_manager.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_manager.isemailIdentify
     *
     * @return the value of ssm_manager.isemailIdentify
     *
     * @mbggenerated
     */
    public String getIsemailidentify() {
        return isemailidentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_manager.isemailIdentify
     *
     * @param isemailidentify the value for ssm_manager.isemailIdentify
     *
     * @mbggenerated
     */
    public void setIsemailidentify(String isemailidentify) {
        this.isemailidentify = isemailidentify == null ? null : isemailidentify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_manager.isphoneIdentify
     *
     * @return the value of ssm_manager.isphoneIdentify
     *
     * @mbggenerated
     */
    public String getIsphoneidentify() {
        return isphoneidentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_manager.isphoneIdentify
     *
     * @param isphoneidentify the value for ssm_manager.isphoneIdentify
     *
     * @mbggenerated
     */
    public void setIsphoneidentify(String isphoneidentify) {
        this.isphoneidentify = isphoneidentify == null ? null : isphoneidentify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_manager.managersex
     *
     * @return the value of ssm_manager.managersex
     *
     * @mbggenerated
     */
    public String getManagersex() {
        return managersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_manager.managersex
     *
     * @param managersex the value for ssm_manager.managersex
     *
     * @mbggenerated
     */
    public void setManagersex(String managersex) {
        this.managersex = managersex == null ? null : managersex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_manager.managerbrith
     *
     * @return the value of ssm_manager.managerbrith
     *
     * @mbggenerated
     */
    public String getManagerbrith() {
        return managerbrith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_manager.managerbrith
     *
     * @param managerbrith the value for ssm_manager.managerbrith
     *
     * @mbggenerated
     */
    public void setManagerbrith(String managerbrith) {
        this.managerbrith = managerbrith == null ? null : managerbrith.trim();
    }
}