package com.dy.model;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_menu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_menu.menucode
     *
     * @mbggenerated
     */
    private String menucode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_menu.menuname
     *
     * @mbggenerated
     */
    private String menuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_menu.menunamekey
     *
     * @mbggenerated
     */
    private String menunamekey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_menu.sortnum
     *
     * @mbggenerated
     */
    private Integer sortnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_menu.ownertype
     *
     * @mbggenerated
     */
    private String ownertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_menu.menudesc
     *
     * @mbggenerated
     */
    private String menudesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_menu.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_menu.id
     *
     * @return the value of ssm_menu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_menu.id
     *
     * @param id the value for ssm_menu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_menu.menucode
     *
     * @return the value of ssm_menu.menucode
     *
     * @mbggenerated
     */
    public String getMenucode() {
        return menucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_menu.menucode
     *
     * @param menucode the value for ssm_menu.menucode
     *
     * @mbggenerated
     */
    public void setMenucode(String menucode) {
        this.menucode = menucode == null ? null : menucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_menu.menuname
     *
     * @return the value of ssm_menu.menuname
     *
     * @mbggenerated
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_menu.menuname
     *
     * @param menuname the value for ssm_menu.menuname
     *
     * @mbggenerated
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_menu.menunamekey
     *
     * @return the value of ssm_menu.menunamekey
     *
     * @mbggenerated
     */
    public String getMenunamekey() {
        return menunamekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_menu.menunamekey
     *
     * @param menunamekey the value for ssm_menu.menunamekey
     *
     * @mbggenerated
     */
    public void setMenunamekey(String menunamekey) {
        this.menunamekey = menunamekey == null ? null : menunamekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_menu.sortnum
     *
     * @return the value of ssm_menu.sortnum
     *
     * @mbggenerated
     */
    public Integer getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_menu.sortnum
     *
     * @param sortnum the value for ssm_menu.sortnum
     *
     * @mbggenerated
     */
    public void setSortnum(Integer sortnum) {
        this.sortnum = sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_menu.ownertype
     *
     * @return the value of ssm_menu.ownertype
     *
     * @mbggenerated
     */
    public String getOwnertype() {
        return ownertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_menu.ownertype
     *
     * @param ownertype the value for ssm_menu.ownertype
     *
     * @mbggenerated
     */
    public void setOwnertype(String ownertype) {
        this.ownertype = ownertype == null ? null : ownertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_menu.menudesc
     *
     * @return the value of ssm_menu.menudesc
     *
     * @mbggenerated
     */
    public String getMenudesc() {
        return menudesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_menu.menudesc
     *
     * @param menudesc the value for ssm_menu.menudesc
     *
     * @mbggenerated
     */
    public void setMenudesc(String menudesc) {
        this.menudesc = menudesc == null ? null : menudesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_menu.position
     *
     * @return the value of ssm_menu.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_menu.position
     *
     * @param position the value for ssm_menu.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }
	public String toString() {
		return "Menu [id=" + id + ", menucode=" + menucode + ", menuname="
				+ menuname + ", menunamekey=" + menunamekey + ", sortnum="
				+ sortnum + ", ownertype=" + ownertype + ", menudesc="
				+ menudesc + "]";
	}
}