package com.dy.model;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.orderid
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.patientid
     *
     * @mbggenerated
     */
    private Integer patientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.doctorid
     *
     * @mbggenerated
     */
    private Integer doctorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.subjectid
     *
     * @mbggenerated
     */
    private Integer subjectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.orderdate
     *
     * @mbggenerated
     */
    private String orderdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.orderstate
     *
     * @mbggenerated
     */
    private String orderstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.orderid
     *
     * @return the value of ssm_order.orderid
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.orderid
     *
     * @param orderid the value for ssm_order.orderid
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.patientid
     *
     * @return the value of ssm_order.patientid
     *
     * @mbggenerated
     */
    public Integer getPatientid() {
        return patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.patientid
     *
     * @param patientid the value for ssm_order.patientid
     *
     * @mbggenerated
     */
    public void setPatientid(Integer patientid) {
        this.patientid = patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.doctorid
     *
     * @return the value of ssm_order.doctorid
     *
     * @mbggenerated
     */
    public Integer getDoctorid() {
        return doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.doctorid
     *
     * @param doctorid the value for ssm_order.doctorid
     *
     * @mbggenerated
     */
    public void setDoctorid(Integer doctorid) {
        this.doctorid = doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.subjectid
     *
     * @return the value of ssm_order.subjectid
     *
     * @mbggenerated
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.subjectid
     *
     * @param subjectid the value for ssm_order.subjectid
     *
     * @mbggenerated
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.orderdate
     *
     * @return the value of ssm_order.orderdate
     *
     * @mbggenerated
     */
    public String getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.orderdate
     *
     * @param orderdate the value for ssm_order.orderdate
     *
     * @mbggenerated
     */
    public void setOrderdate(String orderdate) {
        this.orderdate = orderdate == null ? null : orderdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.orderstate
     *
     * @return the value of ssm_order.orderstate
     *
     * @mbggenerated
     */
    public String getOrderstate() {
        return orderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.orderstate
     *
     * @param orderstate the value for ssm_order.orderstate
     *
     * @mbggenerated
     */
    public void setOrderstate(String orderstate) {
        this.orderstate = orderstate == null ? null : orderstate.trim();
    }
}