package com.dy.model;

public class Patient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_patient.patientid
     *
     * @mbggenerated
     */
    private Integer patientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_patient.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_patient.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_patient.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_patient.weight
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_patient.brith
     *
     * @mbggenerated
     */
    private String brith;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_patient.nation
     *
     * @mbggenerated
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_patient.IDCardnum
     *
     * @mbggenerated
     */
    private String idcardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_patient.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_patient.phonenum
     *
     * @mbggenerated
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_patient.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_patient.isemailIdentify
     *
     * @mbggenerated
     */
    private String isemailidentify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_patient.isphoneIdentify
     *
     * @mbggenerated
     */
    private String isphoneidentify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_patient.anaphylactogen
     *
     * @mbggenerated
     */
    private String anaphylactogen;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_patient.patientid
     *
     * @return the value of ssm_patient.patientid
     *
     * @mbggenerated
     */
    public Integer getPatientid() {
        return patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_patient.patientid
     *
     * @param patientid the value for ssm_patient.patientid
     *
     * @mbggenerated
     */
    public void setPatientid(Integer patientid) {
        this.patientid = patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_patient.userid
     *
     * @return the value of ssm_patient.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_patient.userid
     *
     * @param userid the value for ssm_patient.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_patient.name
     *
     * @return the value of ssm_patient.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_patient.name
     *
     * @param name the value for ssm_patient.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_patient.sex
     *
     * @return the value of ssm_patient.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_patient.sex
     *
     * @param sex the value for ssm_patient.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_patient.weight
     *
     * @return the value of ssm_patient.weight
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_patient.weight
     *
     * @param weight the value for ssm_patient.weight
     *
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_patient.brith
     *
     * @return the value of ssm_patient.brith
     *
     * @mbggenerated
     */
    public String getBrith() {
        return brith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_patient.brith
     *
     * @param brith the value for ssm_patient.brith
     *
     * @mbggenerated
     */
    public void setBrith(String brith) {
        this.brith = brith == null ? null : brith.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_patient.nation
     *
     * @return the value of ssm_patient.nation
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_patient.nation
     *
     * @param nation the value for ssm_patient.nation
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_patient.IDCardnum
     *
     * @return the value of ssm_patient.IDCardnum
     *
     * @mbggenerated
     */
    public String getIdcardnum() {
        return idcardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_patient.IDCardnum
     *
     * @param idcardnum the value for ssm_patient.IDCardnum
     *
     * @mbggenerated
     */
    public void setIdcardnum(String idcardnum) {
        this.idcardnum = idcardnum == null ? null : idcardnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_patient.address
     *
     * @return the value of ssm_patient.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_patient.address
     *
     * @param address the value for ssm_patient.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_patient.phonenum
     *
     * @return the value of ssm_patient.phonenum
     *
     * @mbggenerated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_patient.phonenum
     *
     * @param phonenum the value for ssm_patient.phonenum
     *
     * @mbggenerated
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_patient.email
     *
     * @return the value of ssm_patient.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_patient.email
     *
     * @param email the value for ssm_patient.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_patient.isemailIdentify
     *
     * @return the value of ssm_patient.isemailIdentify
     *
     * @mbggenerated
     */
    public String getIsemailidentify() {
        return isemailidentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_patient.isemailIdentify
     *
     * @param isemailidentify the value for ssm_patient.isemailIdentify
     *
     * @mbggenerated
     */
    public void setIsemailidentify(String isemailidentify) {
        this.isemailidentify = isemailidentify == null ? null : isemailidentify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_patient.isphoneIdentify
     *
     * @return the value of ssm_patient.isphoneIdentify
     *
     * @mbggenerated
     */
    public String getIsphoneidentify() {
        return isphoneidentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_patient.isphoneIdentify
     *
     * @param isphoneidentify the value for ssm_patient.isphoneIdentify
     *
     * @mbggenerated
     */
    public void setIsphoneidentify(String isphoneidentify) {
        this.isphoneidentify = isphoneidentify == null ? null : isphoneidentify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_patient.anaphylactogen
     *
     * @return the value of ssm_patient.anaphylactogen
     *
     * @mbggenerated
     */
    public String getAnaphylactogen() {
        return anaphylactogen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_patient.anaphylactogen
     *
     * @param anaphylactogen the value for ssm_patient.anaphylactogen
     *
     * @mbggenerated
     */
    public void setAnaphylactogen(String anaphylactogen) {
        this.anaphylactogen = anaphylactogen == null ? null : anaphylactogen.trim();
    }
}