package com.dy.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user.usertype
     *
     * @mbggenerated
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user.registertime
     *
     * @mbggenerated
     */
    private String registertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user.lastlogintime
     *
     * @mbggenerated
     */
    private String lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user.logintimes
     *
     * @mbggenerated
     */
    private Integer logintimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user.userid
     *
     * @return the value of ssm_user.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user.userid
     *
     * @param userid the value for ssm_user.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user.username
     *
     * @return the value of ssm_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user.username
     *
     * @param username the value for ssm_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user.password
     *
     * @return the value of ssm_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user.password
     *
     * @param password the value for ssm_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user.usertype
     *
     * @return the value of ssm_user.usertype
     *
     * @mbggenerated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user.usertype
     *
     * @param usertype the value for ssm_user.usertype
     *
     * @mbggenerated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user.registertime
     *
     * @return the value of ssm_user.registertime
     *
     * @mbggenerated
     */
    public String getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user.registertime
     *
     * @param registertime the value for ssm_user.registertime
     *
     * @mbggenerated
     */
    public void setRegistertime(String registertime) {
        this.registertime = registertime == null ? null : registertime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user.lastlogintime
     *
     * @return the value of ssm_user.lastlogintime
     *
     * @mbggenerated
     */
    public String getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user.lastlogintime
     *
     * @param lastlogintime the value for ssm_user.lastlogintime
     *
     * @mbggenerated
     */
    public void setLastlogintime(String lastlogintime) {
        this.lastlogintime = lastlogintime == null ? null : lastlogintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user.logintimes
     *
     * @return the value of ssm_user.logintimes
     *
     * @mbggenerated
     */
    public Integer getLogintimes() {
        return logintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user.logintimes
     *
     * @param logintimes the value for ssm_user.logintimes
     *
     * @mbggenerated
     */
    public void setLogintimes(Integer logintimes) {
        this.logintimes = logintimes;
    }
}