package com.dy.model;

public class AdviceFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_adviceflow.adviceflowid
     *
     * @mbggenerated
     */
    private Integer adviceflowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_adviceflow.adviceid
     *
     * @mbggenerated
     */
    private Integer adviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_adviceflow.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_adviceflow.advicedate
     *
     * @mbggenerated
     */
    private Integer advicedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_adviceflow.advicecontent
     *
     * @mbggenerated
     */
    private String advicecontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_adviceflow.adviceflowid
     *
     * @return the value of ssm_adviceflow.adviceflowid
     *
     * @mbggenerated
     */
    public Integer getAdviceflowid() {
        return adviceflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_adviceflow.adviceflowid
     *
     * @param adviceflowid the value for ssm_adviceflow.adviceflowid
     *
     * @mbggenerated
     */
    public void setAdviceflowid(Integer adviceflowid) {
        this.adviceflowid = adviceflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_adviceflow.adviceid
     *
     * @return the value of ssm_adviceflow.adviceid
     *
     * @mbggenerated
     */
    public Integer getAdviceid() {
        return adviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_adviceflow.adviceid
     *
     * @param adviceid the value for ssm_adviceflow.adviceid
     *
     * @mbggenerated
     */
    public void setAdviceid(Integer adviceid) {
        this.adviceid = adviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_adviceflow.userid
     *
     * @return the value of ssm_adviceflow.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_adviceflow.userid
     *
     * @param userid the value for ssm_adviceflow.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_adviceflow.advicedate
     *
     * @return the value of ssm_adviceflow.advicedate
     *
     * @mbggenerated
     */
    public Integer getAdvicedate() {
        return advicedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_adviceflow.advicedate
     *
     * @param advicedate the value for ssm_adviceflow.advicedate
     *
     * @mbggenerated
     */
    public void setAdvicedate(Integer advicedate) {
        this.advicedate = advicedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_adviceflow.advicecontent
     *
     * @return the value of ssm_adviceflow.advicecontent
     *
     * @mbggenerated
     */
    public String getAdvicecontent() {
        return advicecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_adviceflow.advicecontent
     *
     * @param advicecontent the value for ssm_adviceflow.advicecontent
     *
     * @mbggenerated
     */
    public void setAdvicecontent(String advicecontent) {
        this.advicecontent = advicecontent == null ? null : advicecontent.trim();
    }
}