package com.dy.model;

public class Case {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_case.caseid
     *
     * @mbggenerated
     */
    private Integer caseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_case.orderid
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_case.adivceid
     *
     * @mbggenerated
     */
    private Integer adivceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_case.patientid
     *
     * @mbggenerated
     */
    private Integer patientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_case.doctorid
     *
     * @mbggenerated
     */
    private Integer doctorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_case.isfirst
     *
     * @mbggenerated
     */
    private Integer isfirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_case.subjectid
     *
     * @mbggenerated
     */
    private Integer subjectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_case.visitdate
     *
     * @mbggenerated
     */
    private String visitdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_case.diagnosis
     *
     * @mbggenerated
     */
    private String diagnosis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_case.treat
     *
     * @mbggenerated
     */
    private String treat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_case.caseid
     *
     * @return the value of ssm_case.caseid
     *
     * @mbggenerated
     */
    public Integer getCaseid() {
        return caseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_case.caseid
     *
     * @param caseid the value for ssm_case.caseid
     *
     * @mbggenerated
     */
    public void setCaseid(Integer caseid) {
        this.caseid = caseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_case.orderid
     *
     * @return the value of ssm_case.orderid
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_case.orderid
     *
     * @param orderid the value for ssm_case.orderid
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_case.adivceid
     *
     * @return the value of ssm_case.adivceid
     *
     * @mbggenerated
     */
    public Integer getAdivceid() {
        return adivceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_case.adivceid
     *
     * @param adivceid the value for ssm_case.adivceid
     *
     * @mbggenerated
     */
    public void setAdivceid(Integer adivceid) {
        this.adivceid = adivceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_case.patientid
     *
     * @return the value of ssm_case.patientid
     *
     * @mbggenerated
     */
    public Integer getPatientid() {
        return patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_case.patientid
     *
     * @param patientid the value for ssm_case.patientid
     *
     * @mbggenerated
     */
    public void setPatientid(Integer patientid) {
        this.patientid = patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_case.doctorid
     *
     * @return the value of ssm_case.doctorid
     *
     * @mbggenerated
     */
    public Integer getDoctorid() {
        return doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_case.doctorid
     *
     * @param doctorid the value for ssm_case.doctorid
     *
     * @mbggenerated
     */
    public void setDoctorid(Integer doctorid) {
        this.doctorid = doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_case.isfirst
     *
     * @return the value of ssm_case.isfirst
     *
     * @mbggenerated
     */
    public Integer getIsfirst() {
        return isfirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_case.isfirst
     *
     * @param isfirst the value for ssm_case.isfirst
     *
     * @mbggenerated
     */
    public void setIsfirst(Integer isfirst) {
        this.isfirst = isfirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_case.subjectid
     *
     * @return the value of ssm_case.subjectid
     *
     * @mbggenerated
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_case.subjectid
     *
     * @param subjectid the value for ssm_case.subjectid
     *
     * @mbggenerated
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_case.visitdate
     *
     * @return the value of ssm_case.visitdate
     *
     * @mbggenerated
     */
    public String getVisitdate() {
        return visitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_case.visitdate
     *
     * @param visitdate the value for ssm_case.visitdate
     *
     * @mbggenerated
     */
    public void setVisitdate(String visitdate) {
        this.visitdate = visitdate == null ? null : visitdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_case.diagnosis
     *
     * @return the value of ssm_case.diagnosis
     *
     * @mbggenerated
     */
    public String getDiagnosis() {
        return diagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_case.diagnosis
     *
     * @param diagnosis the value for ssm_case.diagnosis
     *
     * @mbggenerated
     */
    public void setDiagnosis(String diagnosis) {
        this.diagnosis = diagnosis == null ? null : diagnosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_case.treat
     *
     * @return the value of ssm_case.treat
     *
     * @mbggenerated
     */
    public String getTreat() {
        return treat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_case.treat
     *
     * @param treat the value for ssm_case.treat
     *
     * @mbggenerated
     */
    public void setTreat(String treat) {
        this.treat = treat == null ? null : treat.trim();
    }
}