package com.dy.model;

public class Doctor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_doctor.doctorid
     *
     * @mbggenerated
     */
    private Integer doctorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_doctor.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_doctor.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_doctor.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_doctor.brith
     *
     * @mbggenerated
     */
    private String brith;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_doctor.subjectid
     *
     * @mbggenerated
     */
    private Integer subjectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_doctor.professionid
     *
     * @mbggenerated
     */
    private Integer professionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_doctor.phonenum
     *
     * @mbggenerated
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_doctor.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_doctor.isphoneIdentify
     *
     * @mbggenerated
     */
    private String isphoneidentify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_doctor.isemailIdentify
     *
     * @mbggenerated
     */
    private String isemailidentify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_doctor.goodat
     *
     * @mbggenerated
     */
    private String goodat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_doctor.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_doctor.doctorid
     *
     * @return the value of ssm_doctor.doctorid
     *
     * @mbggenerated
     */
    public Integer getDoctorid() {
        return doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_doctor.doctorid
     *
     * @param doctorid the value for ssm_doctor.doctorid
     *
     * @mbggenerated
     */
    public void setDoctorid(Integer doctorid) {
        this.doctorid = doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_doctor.userid
     *
     * @return the value of ssm_doctor.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_doctor.userid
     *
     * @param userid the value for ssm_doctor.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_doctor.realname
     *
     * @return the value of ssm_doctor.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_doctor.realname
     *
     * @param realname the value for ssm_doctor.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_doctor.sex
     *
     * @return the value of ssm_doctor.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_doctor.sex
     *
     * @param sex the value for ssm_doctor.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_doctor.brith
     *
     * @return the value of ssm_doctor.brith
     *
     * @mbggenerated
     */
    public String getBrith() {
        return brith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_doctor.brith
     *
     * @param brith the value for ssm_doctor.brith
     *
     * @mbggenerated
     */
    public void setBrith(String brith) {
        this.brith = brith == null ? null : brith.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_doctor.subjectid
     *
     * @return the value of ssm_doctor.subjectid
     *
     * @mbggenerated
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_doctor.subjectid
     *
     * @param subjectid the value for ssm_doctor.subjectid
     *
     * @mbggenerated
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_doctor.professionid
     *
     * @return the value of ssm_doctor.professionid
     *
     * @mbggenerated
     */
    public Integer getProfessionid() {
        return professionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_doctor.professionid
     *
     * @param professionid the value for ssm_doctor.professionid
     *
     * @mbggenerated
     */
    public void setProfessionid(Integer professionid) {
        this.professionid = professionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_doctor.phonenum
     *
     * @return the value of ssm_doctor.phonenum
     *
     * @mbggenerated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_doctor.phonenum
     *
     * @param phonenum the value for ssm_doctor.phonenum
     *
     * @mbggenerated
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_doctor.email
     *
     * @return the value of ssm_doctor.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_doctor.email
     *
     * @param email the value for ssm_doctor.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_doctor.isphoneIdentify
     *
     * @return the value of ssm_doctor.isphoneIdentify
     *
     * @mbggenerated
     */
    public String getIsphoneidentify() {
        return isphoneidentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_doctor.isphoneIdentify
     *
     * @param isphoneidentify the value for ssm_doctor.isphoneIdentify
     *
     * @mbggenerated
     */
    public void setIsphoneidentify(String isphoneidentify) {
        this.isphoneidentify = isphoneidentify == null ? null : isphoneidentify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_doctor.isemailIdentify
     *
     * @return the value of ssm_doctor.isemailIdentify
     *
     * @mbggenerated
     */
    public String getIsemailidentify() {
        return isemailidentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_doctor.isemailIdentify
     *
     * @param isemailidentify the value for ssm_doctor.isemailIdentify
     *
     * @mbggenerated
     */
    public void setIsemailidentify(String isemailidentify) {
        this.isemailidentify = isemailidentify == null ? null : isemailidentify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_doctor.goodat
     *
     * @return the value of ssm_doctor.goodat
     *
     * @mbggenerated
     */
    public String getGoodat() {
        return goodat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_doctor.goodat
     *
     * @param goodat the value for ssm_doctor.goodat
     *
     * @mbggenerated
     */
    public void setGoodat(String goodat) {
        this.goodat = goodat == null ? null : goodat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_doctor.summary
     *
     * @return the value of ssm_doctor.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_doctor.summary
     *
     * @param summary the value for ssm_doctor.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }
}