package com.dy.model;

public class Medicinal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_medicinal.medicinalid
     *
     * @mbggenerated
     */
    private Integer medicinalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_medicinal.medicinalname
     *
     * @mbggenerated
     */
    private String medicinalname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_medicinal.medicinalprice
     *
     * @mbggenerated
     */
    private Integer medicinalprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_medicinal.medicinalid
     *
     * @return the value of ssm_medicinal.medicinalid
     *
     * @mbggenerated
     */
    public Integer getMedicinalid() {
        return medicinalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_medicinal.medicinalid
     *
     * @param medicinalid the value for ssm_medicinal.medicinalid
     *
     * @mbggenerated
     */
    public void setMedicinalid(Integer medicinalid) {
        this.medicinalid = medicinalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_medicinal.medicinalname
     *
     * @return the value of ssm_medicinal.medicinalname
     *
     * @mbggenerated
     */
    public String getMedicinalname() {
        return medicinalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_medicinal.medicinalname
     *
     * @param medicinalname the value for ssm_medicinal.medicinalname
     *
     * @mbggenerated
     */
    public void setMedicinalname(String medicinalname) {
        this.medicinalname = medicinalname == null ? null : medicinalname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_medicinal.medicinalprice
     *
     * @return the value of ssm_medicinal.medicinalprice
     *
     * @mbggenerated
     */
    public Integer getMedicinalprice() {
        return medicinalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_medicinal.medicinalprice
     *
     * @param medicinalprice the value for ssm_medicinal.medicinalprice
     *
     * @mbggenerated
     */
    public void setMedicinalprice(Integer medicinalprice) {
        this.medicinalprice = medicinalprice;
    }
}