package com.dy.model;

public class Profession {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_profession.professionid
     *
     * @mbggenerated
     */
    private Integer professionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_profession.professionname
     *
     * @mbggenerated
     */
    private String professionname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_profession.professionid
     *
     * @return the value of ssm_profession.professionid
     *
     * @mbggenerated
     */
    public Integer getProfessionid() {
        return professionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_profession.professionid
     *
     * @param professionid the value for ssm_profession.professionid
     *
     * @mbggenerated
     */
    public void setProfessionid(Integer professionid) {
        this.professionid = professionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_profession.professionname
     *
     * @return the value of ssm_profession.professionname
     *
     * @mbggenerated
     */
    public String getProfessionname() {
        return professionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_profession.professionname
     *
     * @param professionname the value for ssm_profession.professionname
     *
     * @mbggenerated
     */
    public void setProfessionname(String professionname) {
        this.professionname = professionname == null ? null : professionname.trim();
    }
}