package com.dy.model;

public class Subject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_subject.subjectid
     *
     * @mbggenerated
     */
    private Integer subjectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_subject.subjectname
     *
     * @mbggenerated
     */
    private String subjectname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_subject.subjectintruction
     *
     * @mbggenerated
     */
    private String subjectintruction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_subject.subjectid
     *
     * @return the value of ssm_subject.subjectid
     *
     * @mbggenerated
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_subject.subjectid
     *
     * @param subjectid the value for ssm_subject.subjectid
     *
     * @mbggenerated
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_subject.subjectname
     *
     * @return the value of ssm_subject.subjectname
     *
     * @mbggenerated
     */
    public String getSubjectname() {
        return subjectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_subject.subjectname
     *
     * @param subjectname the value for ssm_subject.subjectname
     *
     * @mbggenerated
     */
    public void setSubjectname(String subjectname) {
        this.subjectname = subjectname == null ? null : subjectname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_subject.subjectintruction
     *
     * @return the value of ssm_subject.subjectintruction
     *
     * @mbggenerated
     */
    public String getSubjectintruction() {
        return subjectintruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_subject.subjectintruction
     *
     * @param subjectintruction the value for ssm_subject.subjectintruction
     *
     * @mbggenerated
     */
    public void setSubjectintruction(String subjectintruction) {
        this.subjectintruction = subjectintruction == null ? null : subjectintruction.trim();
    }
}