package com.dy.dao;

import java.util.List;

import com.dy.model.Patient;

public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer patientid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated
     */
    int insert(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated
     */
    int insertSelective(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated
     */
    Patient selectByPrimaryKey(Integer patientid);
    Patient selectPatientByUserid(Integer patientid);
    
    List<Patient> selectAllPatient();

    int updateByPrimaryKeySelective(Patient record);
    int updateByPrimaryKey(Patient record);
}